# On push to main, checkout "pages" branch and work in it.

name: Build and Push Documents

on:
  push:
    branches:
      - main
env:
  ref: refs/heads/pages
  dest: ./docs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
          fetch-depth: 0

      - name: Git Setup
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge from main
        run: |
          git merge --no-ff ${GITHUB_SHA}

      - name: Build
        uses: docker://pandoc/core:latest
        with:
          entrypoint: make

      - name: Move
        run: |
          mv ./build/index.html ${{ env.dest }}

      - name: Git Add
        run: |
          git add ${{ env.dest }}

      - name: Git Commit
        continue-on-error: true
        run: |
          git commit -m "Update for ${GITHUB_REF} ${GITHUB_SHA}" -m "Automatic push by github actions"

      - name: Git Push
        run: |
          git push origin HEAD:${{ env.ref }}
